# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0
version: '3.8'

services:
  etcd:
    image: docker.io/bitnami/etcd:3.5
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd_data:/bitnami/etcd
volumes:
  etcd_data:
    driver: local
