version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - internal

networks:
  internal:
    external: true