version: '3'

services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    hostname: nginx
    domainname: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./out:/var/www/out
    networks:
      - internal

networks:
  internal:
    external: true