version: '2'

services:
  nginx:
    # image: nginx:latest
    container_name: nginx-service-1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    networks:
      - internal
    user: "www-data:www-data"

networks:
  internal:
    driver: bridge