version: '2'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-service
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/sites-available/default.conf
      - ./out:/var/www/out
    networks:
      - internal

networks:
  internal:
    driver: bridge