version: '2'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-service
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    networks:
      - internal

networks:
  internal:
    driver: bridge