# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '3'

services:
  minio:
    image: docker.io/bitnami/minio:latest
    container_name: minio
    hostname: minio
    domainname: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    networks:
      - internal

volumes:
  minio_data:
    driver: local

networks:
  internal:
    driver: bridge