version: '3.8'
services:
  db:
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    networks:
      - internal
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kuroshibaz
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    env_file:
      - .env
    networks:
      - internal
        
volumes:
  data:
    driver: local

networks:
  internal:
    external: true